### ISSUE TITLE
Change disqus code to just the ID instead of the whole HTML embed

### ISSUE THREAD

**Issue by piedoom** [piedoom/feather#17]
https://github.com/piedoom/feather/commit/1271f525d4935ebbb29ce5a13011ca45496603a7#diff-618063036395fe9ee107f22b46c9eadeR25

https://github.com/piedoom/feather/blob/e4b2c08b33023a237998354adfc0f8a43c1eb041/templates/page.html#L32

**Comment by reivilibre** [comment]
On the other hand, leaving the embed as-is means that a Disqus alternative can easily be integrated, right?

**Comment by piedoom** [comment]
that's true, however integrating HTML in the TOML file isn't that great of an experience.  I can look into providing alternate methods later too, otherwise just modifying a template may be the best course of action.
